{
    'name': "Fiscalization Service",
    'author': 'ErpMstar Solutions',
    'category': 'Point of Sale',
    'summary': """""",
    'license': 'AGPL-3',
    'version': '1.2',
    'depends': ['sale', 'point_of_sale', 'fiscalization_base', 'pos_operating_unit'],
    'data': [
        'security/ir.model.access.csv',
        'views/pos_config_view.xml',
        'views/pos_order_view.xml',
        'views/res_users_view.xml',
        'views/cash_in_out.xml',
        'views/report_invoice.xml',
        'views/res_company_view.xml',
        'views/pos_session_view.xml',
        'data/fiscalization_cron.xml',
    ],
    'assets': {
        'point_of_sale.assets': [
            "fiscalization/static/src/lib/notify.min.js",
            "fiscalization/static/src/lib/qrious.min.js",
            "fiscalization/static/src/lib/forge.min.js",
            "fiscalization/static/src/js/pos_receipt.js",
            "fiscalization/static/src/js/cash_opening.js",
            "fiscalization/static/src/js/TransporterInfoButton.js",
            "fiscalization/static/src/js/TransporterInfoPopup.js",
        ],
        'web.assets_qweb': [
            'fiscalization/static/src/xml/OrderReceipt.xml',
            'fiscalization/static/src/xml/CashOpeningPopup.xml',
            'fiscalization/static/src/xml/TransporterInfoButton.xml',
            'fiscalization/static/src/xml/TransporterInfoPopup.xml',
        ],
    },
    'images': [],
    'installable': True,
    'application': True,
    'auto_install': False,
}
